baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Coding for kids'
enableGitinfo = true

[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[markup]
  [markup.highlight]
    style = 'catppuccin-latte'

[params]
  showVisitedLinks = true
  collapsibleMenu = true

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/alienp4nda/code-for-kids"
weight = 10